[project]
name = "uvmono-cli"
version = "0.1.0"
description = "A cli interface"
authors = [
    { name = "Shawn O'Hare", email = "shawn@shawnohare.com" }
]
requires-python = ">=3.12"
dependencies = [
    "uvmono-core",
]

[project.scripts]
uvmono = "uvmono_cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
uvmono-core = { workspace = true }

# if using namespace packages and hatch, add below to specify target.
# This is problematic if the name changes
# [tool.hatch.build.targets.wheel]
# packages = ["src/uvmonons"]

