[project]
name = "uvmono-runtime"
version = "0.1.0"
description = "Common target runtimes defining dependencies required for projects."
readme = "README.md"
authors = [
    { name = "Shawn O'Hare", email = "shawn@shawnohare.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cowsay==6.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
