[project]
name = "uvmono-ml"
version = "0.1.1"
description = "Example project representing an ml inference task."
readme = "README.md"
authors = [
    { name = "Shawn O'Hare", email = "shawn@shawnohare.com" }
]
requires-python = ">=3.12"
dependencies = [
    "uvmono-lib1",
    "uvmono-ml-core",
    "uvmono-runtime",
    # a project specific dependency. Might conflict with other projects.
    "idna==3.10",
]

[project.optional-dependencies]
train = [
    "evaluate<0.5",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "uvmono-dev",
]

# Explicitly list workspace members for each project so that
# uv build --all-packages will generate required dists for this project.
# Useful in contexts where wheels need to be bundled into a runtime.
[tool.uv.workspace]
members = [
    "packages/*",
    "../shared/uvmono-lib1",
    "../deps/uvmono-runtime",
]

[tool.uv.sources]
uvmono-lib1 = { workspace = true }
uvmono-ml-core = { workspace = true }
# uvmono-runtime = { workspace = true }
uvmono-runtime = { workspace = true }
# dev deps are not workspace members so they are not built
uvmono-dev = { path = "../deps/uvmono-dev", editable = true }

